/**
 * Catalog build script (docs/SPEC.md §5). Run with `npm run build:catalog`.
 *
 * Pulls free-exercise-db, filters to the bodyweight pool, applies the
 * curation in scripts/curation.yaml, downloads and converts images to WebP,
 * and emits src/lib/catalog/{catalog,attribution}.json plus static/media/**.
 *
 * Deterministic: same inputs produce byte-identical output.
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { parse as parseYaml } from 'yaml';
import type { Attribution, EquipmentId, Exercise, MediaAsset } from '../src/lib/types.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_JSON = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';
// NOTE: images live under main/exercises/, NOT main/dist/exercises/ (verified, see docs/M0-findings.md)
const IMAGE_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';
const MAX_EDGE = 800;
const WEBP_QUALITY = 80;
// Mean per-pixel difference (0-255) below which two frames count as the same
// photo. Genuinely distinct frames in this source score 4 and up; re-used
// photographs score 0.
const DUPLICATE_THRESHOLD = 1.5;

interface SourceExercise {
	id: string;
	name: string;
	force: string | null;
	level: 'beginner' | 'intermediate' | 'expert';
	mechanic: string | null;
	equipment: string | null;
	primaryMuscles: string[];
	secondaryMuscles: string[];
	instructions: string[];
	category: string;
	images: string[];
}

interface Curation {
	/** Per-type exercise budgets, including `ungated` (§5.1). */
	budgets: Record<string, number>;
	/** Source `name` -> the equipment it needs. Admits and tags in one place. */
	equipment: Record<EquipmentId, string[]>;
	exclude: string[];
	mobility: string[];
	unilateral: string[];
}

/**
 * The gated types (§5.1). `chair` is deliberately absent: it is tagged but never
 * gated, so it neither needs a budget nor satisfies the "must declare a purchase"
 * check below.
 */
const GATED: EquipmentId[] = [
	'pull_up_bar',
	'jumping_rope',
	'dumbbells',
	'kettlebell',
	'resistance_band',
	'foam_roller',
	'yoga_ball',
	'suspension_trainer',
	'ab_wheel'
];

const ALL_EQUIPMENT: EquipmentId[] = [...GATED, 'chair'];

/**
 * Source `equipment` values that mean a gym. §1 puts these out of scope, so a
 * name in curation.yaml that resolves to one of them is a mistake in the file
 * rather than a judgement call — hence a hard error rather than a filter.
 */
const GYM_EQUIPMENT = new Set([
	'machine',
	'cable',
	'barbell',
	'e-z curl bar',
	// `medicine ball` stays: its rows are almost all throws and slams, which need a
	// partner and a room this app is not used in. `exercise ball` was on this list
	// until 2026-07-30 and is not gym equipment — see §5.1's amendment.
	'medicine ball'
]);

/** Source values that need nothing but a floor and a wall. */
const BODYWEIGHT_EQUIPMENT = new Set(['body only', null] as (string | null)[]);

function slugify(name: string): string {
	return name
		.toLowerCase()
		.normalize('NFKD')
		.replace(/[̀-ͯ]/g, '')
		.replace(/['’]/g, '') // "world's" -> "worlds", not "world_s"
		.replace(/[^a-z0-9]+/g, '_')
		.replace(/^_+|_+$/g, '');
}

function normalizeAlias(s: string): string {
	return s
		.toLowerCase()
		.normalize('NFKD')
		.replace(/[̀-ͯ]/g, '')
		.replace(/[^a-z0-9]+/g, ' ')
		.trim();
}

/** Downscaled greyscale fingerprint, used to spot re-used photographs. */
async function signature(webp: Buffer): Promise<Buffer> {
	return sharp(webp).resize(64, 64, { fit: 'fill' }).greyscale().raw().toBuffer();
}

function meanAbsDiff(a: Buffer, b: Buffer): number {
	let sum = 0;
	for (let i = 0; i < a.length; i++) sum += Math.abs(a[i] - b[i]);
	return sum / a.length;
}

async function fetchJson<T>(url: string): Promise<T> {
	const res = await fetch(url);
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
	return res.json() as Promise<T>;
}

async function fetchWithRetry(url: string, tries = 3): Promise<ArrayBuffer> {
	let lastErr: unknown;
	for (let i = 0; i < tries; i++) {
		try {
			const res = await fetch(url);
			if (!res.ok) throw new Error(`${res.status} for ${url}`);
			return await res.arrayBuffer();
		} catch (err) {
			lastErr = err;
			await new Promise((r) => setTimeout(r, 1000 * (i + 1)));
		}
	}
	throw lastErr;
}

export const MUSCLE_FIGURE_ATTRIBUTION = 'body_highlighter_model';
/**
 * The printable sheet's embedded font (§16). Not generated by this script —
 * `scripts/build-fonts.ts` writes the subsets — but attribution.json is the
 * project's one licence register and the About page reads it, so the entry is
 * emitted here rather than in a second register nothing else knows about.
 */
export const SHEET_FONT_ATTRIBUTION = 'noto_sans';

/**
 * The two body figures behind the muscle map (§4.6), from
 * `svelte-body-highlighter` on npm — itself a port of `react-native-body-highlighter`.
 * MIT, © 2022 ELABBASSI Hicham and © 2025 Stefan Poindl.
 *
 * Replaced a pair of Wikimedia anatomical figures on 2026-07-30. Those were
 * greyscale flayed musculature and the user's verdict was that they looked
 * creepy, which they did. These are a flat body model, and they solve the deeper
 * problem too: every muscle is its own `<g>`, so the app recolours the actual
 * muscle instead of floating an approximate ellipse over a drawing.
 *
 * Two transforms on the way in, both so the markup is safe to inline twice on one
 * page:
 *
 * - `id="chest"` becomes `data-part="chest"`. Two figures on a screen would
 *   otherwise both carry `id="neck"`, and duplicate ids are invalid and make
 *   `#neck` ambiguous. An attribute selector does not care.
 * - The hard-coded `fill` and `stroke` values are stripped, so CSS is the only
 *   thing deciding colour. Left in place they win over stylesheet rules in some
 *   engines and it becomes a fight.
 */
const MODEL_PACKAGE = 'svelte-body-highlighter';
const MODEL_VERSION = '5.0.0';
const MODEL_BASE = `https://registry.npmjs.org/${MODEL_PACKAGE}/-/${MODEL_PACKAGE}-${MODEL_VERSION}.tgz`;

/** Strip the baked-in colours and turn ids into attributes (see above). */
function prepareFigure(svg: string): string {
	return svg
		.replace(/\sid="([^"]+)"/g, ' data-part="$1"')
		.replace(/\s(?:fill|stroke)="(?!none)[^"]*"/g, '')
		.replace(/\n\s*\n/g, '\n')
		.trim();
}

async function fetchBodyFigures(): Promise<void> {
	const dir = join(ROOT, 'static/muscles');
	await mkdir(dir, { recursive: true });

	// The tarball rather than a git host: npm is the one registry this build can
	// always reach, and a version-pinned tarball is reproducible.
	const tgz = Buffer.from(await fetchWithRetry(MODEL_BASE));
	const { Readable } = await import('node:stream');
	const { createGunzip } = await import('node:zlib');
	const chunks: Buffer[] = [];
	const gunzip = Readable.from(tgz).pipe(createGunzip());
	for await (const c of gunzip) chunks.push(c as Buffer);
	const tar = Buffer.concat(chunks);

	for (const view of ['front', 'back'] as const) {
		const svg = readFromTar(tar, `package/dist/assets/svg/male-${view}.svg`);
		if (!svg) throw new Error(`male-${view}.svg not found in ${MODEL_PACKAGE}@${MODEL_VERSION}`);
		const prepared = prepareFigure(svg);
		// A truncated or restructured asset would render as a blank figure, which
		// looks like a styling bug rather than a failed fetch. Counting slugs rather
		// than naming one: the two views share no single muscle worth hard-coding —
		// `chest` is front-only, `gluteal` back-only.
		const slugs = new Set(
			[...prepared.matchAll(/data-slug="([^"]+)"/g)].map((m) => m[1])
		);
		if (!prepared.includes('data-part="outline"') || slugs.size < 8) {
			throw new Error(
				`male-${view}.svg is not the expected structure (${slugs.size} muscle groups)`
			);
		}
		await writeFile(join(dir, `${view}.svg`), prepared + '\n');
		console.log(`  body figure: ${view}.svg (${Math.round(prepared.length / 1024)} kB)`);
	}
}

/** Minimal ustar reader: one named file out of an uncompressed tar. */
function readFromTar(tar: Buffer, wanted: string): string | undefined {
	let offset = 0;
	while (offset + 512 <= tar.length) {
		const name = tar.subarray(offset, offset + 100).toString('utf8').replace(/\0.*$/, '');
		if (!name) break;
		const size = parseInt(
			tar.subarray(offset + 124, offset + 136).toString('utf8').replace(/\0.*$/, '').trim() || '0',
			8
		);
		const body = offset + 512;
		if (name === wanted) return tar.subarray(body, body + size).toString('utf8');
		offset = body + Math.ceil(size / 512) * 512;
	}
	return undefined;
}

async function main() {
	const curation = parseYaml(await readFile(join(ROOT, 'scripts/curation.yaml'), 'utf8')) as Curation;
	const manualAliases = parseYaml(await readFile(join(ROOT, 'scripts/aliases.yaml'), 'utf8')) as Record<
		string,
		string[]
	>;

	console.log('Fetching source data...');
	const source = await fetchJson<SourceExercise[]>(SOURCE_JSON);
	const byName = new Map(source.map((e) => [e.name, e]));

	// Equipment tags: source `name` -> what it needs (§5.1). Built before the
	// integrity checks so they can report on it.
	const equipmentOf = new Map<string, EquipmentId[]>();
	for (const id of ALL_EQUIPMENT) {
		for (const name of curation.equipment[id] ?? []) {
			equipmentOf.set(name, [...(equipmentOf.get(name) ?? []), id]);
		}
	}
	for (const id of Object.keys(curation.equipment)) {
		if (!ALL_EQUIPMENT.includes(id as EquipmentId)) {
			throw new Error(`curation.yaml: "${id}" is not an EquipmentId`);
		}
	}

	// Referential integrity of the curation file: every name must exist.
	for (const list of [
		curation.exclude,
		curation.mobility,
		curation.unilateral,
		[...equipmentOf.keys()]
	]) {
		for (const name of list) {
			if (!byName.has(name)) throw new Error(`curation.yaml references unknown exercise: "${name}"`);
		}
	}
	for (const name of Object.keys(manualAliases)) {
		if (!byName.has(name)) throw new Error(`aliases.yaml references unknown exercise: "${name}"`);
	}
	for (const id of GATED) {
		if (curation.budgets[id] === undefined) {
			throw new Error(`curation.yaml: no budget for "${id}"`);
		}
	}
	if (curation.budgets.ungated === undefined) {
		throw new Error('curation.yaml: no `ungated` budget');
	}

	const excluded = new Set(curation.exclude);
	const mobility = new Set(curation.mobility);
	const unilateral = new Set(curation.unilateral);

	// A row is in the pool if it needs nothing, or if curation.yaml has said what
	// it needs. There is no third way in: the old `include:` list admitted rows
	// without recording why they were admissible (§5.1).
	const pool = source.filter(
		(e) => (BODYWEIGHT_EQUIPMENT.has(e.equipment) || equipmentOf.has(e.name)) && !excluded.has(e.name)
	);

	// §5.1: what the build script must refuse.
	for (const e of pool) {
		const tags = equipmentOf.get(e.name) ?? [];

		if (GYM_EQUIPMENT.has(e.equipment ?? '')) {
			throw new Error(
				`"${e.name}" is source equipment "${e.equipment}", which §1 puts out of scope. ` +
					`Remove it from curation.yaml.`
			);
		}

		// The check that catches the mistake worth catching: tagging a dumbbell
		// exercise `chair` and shipping it to somebody who owns no dumbbells.
		if (!BODYWEIGHT_EQUIPMENT.has(e.equipment) && !tags.some((t) => GATED.includes(t))) {
			throw new Error(
				`"${e.name}" is source equipment "${e.equipment}" but carries no gated tag ` +
					`(${tags.length ? tags.join(', ') : 'none'}). Somebody who owns nothing would be shown it.`
			);
		}
	}

	// Per-type budgets. `ungated` is the number §5's ~120 cap is about: what one
	// user sees having ticked no boxes.
	const perType = new Map<string, number>();
	let ungated = 0;
	for (const e of pool) {
		const tags = equipmentOf.get(e.name) ?? [];
		for (const t of tags) perType.set(t, (perType.get(t) ?? 0) + 1);
		if (!tags.some((t) => GATED.includes(t))) ungated++;
	}
	if (ungated > curation.budgets.ungated) {
		throw new Error(
			`${ungated} exercises are reachable with nothing owned, budget is ${curation.budgets.ungated}. Curate harder.`
		);
	}
	for (const id of GATED) {
		const n = perType.get(id) ?? 0;
		if (n > curation.budgets[id]) {
			throw new Error(`${n} ${id} exercises, budget is ${curation.budgets[id]}. Curate harder.`);
		}
		// A gated type with nothing in it is a checkbox in Settings that does
		// nothing when tapped.
		if (n === 0) {
			throw new Error(`"${id}" is gated but has no exercises. Remove the type or curate some in.`);
		}
	}

	// Slug collisions are a hard error (§5).
	const slugs = new Map<string, string>();
	for (const e of pool) {
		const slug = slugify(e.name);
		const existing = slugs.get(slug);
		if (existing) throw new Error(`Slug collision: "${e.name}" and "${existing}" both -> ${slug}`);
		slugs.set(slug, e.name);
	}

	const mediaRoot = join(ROOT, 'static/media');
	await rm(mediaRoot, { recursive: true, force: true });

	const attributionId = 'free_exercise_db';
	const dropped: string[] = [];
	const duplicateFrames: string[] = [];
	const catalog: Exercise[] = [];

	// Bounded concurrency for image downloads.
	const queue = [...pool];
	const workers = Array.from({ length: 8 }, async () => {
		for (;;) {
			const src = queue.shift();
			if (!src) return;
			const id = slugify(src.name);

			const media: MediaAsset[] = [];
			const kept: Buffer[] = []; // signatures of the frames already written
			for (let i = 0; i < src.images.length; i++) {
				try {
					const raw = await fetchWithRetry(IMAGE_BASE + src.images[i]);
					const converted = sharp(Buffer.from(raw)).resize(MAX_EDGE, MAX_EDGE, {
						fit: 'inside',
						withoutEnlargement: true
					});
					const buf = await converted.webp({ quality: WEBP_QUALITY }).toBuffer();

					// Some source entries ship the same photograph twice. Rendering it
					// twice looks like a bug, so keep only the first copy.
					const sig = await signature(buf);
					if (kept.some((k) => meanAbsDiff(k, sig) < DUPLICATE_THRESHOLD)) {
						duplicateFrames.push(`${src.name} [${i}]`);
						continue;
					}
					kept.push(sig);

					const meta = await sharp(buf).metadata();
					const index = media.length;
					await mkdir(join(mediaRoot, id), { recursive: true });
					await writeFile(join(mediaRoot, id, `${index}.webp`), buf);
					media.push({
						kind: 'image',
						path: `/media/${id}/${index}.webp`,
						// No caption: the source does not label its frames, and inferring
						// "Start"/"End" from their order gets it wrong (see docs/M0-findings.md).
						width: meta.width ?? 0,
						height: meta.height ?? 0
					});
				} catch (err) {
					console.error(`  image failed: ${src.name} [${i}]: ${String(err)}`);
				}
			}

			if (media.length === 0) {
				dropped.push(src.name);
				console.error(`DROPPED (zero media): ${src.name}`);
				continue;
			}

			let category: Exercise['category'];
			if (src.category === 'stretching') category = mobility.has(src.name) ? 'mobility' : 'stretch';
			else if (src.category === 'plyometrics' || src.category === 'cardio') category = 'cardio';
			else if (src.category === 'strength' && src.primaryMuscles.includes('abdominals'))
				category = 'core';
			else category = 'strength';

			const aliasSet = new Set<string>();
			aliasSet.add(normalizeAlias(src.name));
			aliasSet.add(id.replace(/_/g, ' '));
			for (const a of manualAliases[src.name] ?? []) aliasSet.add(normalizeAlias(a));

			catalog.push({
				id,
				name: src.name,
				aliases: [...aliasSet].sort(),
				category,
				// Sorted so the output stays byte-identical regardless of the order the
				// lists happen to be read in.
				equipment: [...(equipmentOf.get(src.name) ?? [])].sort(),
				primaryMuscles: src.primaryMuscles,
				secondaryMuscles: src.secondaryMuscles,
				level: src.level === 'expert' ? 'advanced' : src.level,
				unilateral: unilateral.has(src.name),
				defaultMetric:
					category === 'stretch' || category === 'mobility' || src.force === 'static'
						? 'duration'
						: 'reps',
				instructions: src.instructions,
				media,
				attributionId
			});
		}
	});
	await Promise.all(workers);

	catalog.sort((a, b) => a.id.localeCompare(b.id));

	await fetchBodyFigures();

	const attribution: Attribution[] = [
		{
			id: attributionId,
			source: 'free-exercise-db',
			license: 'PD',
			sourceUrl: 'https://github.com/yuhonas/free-exercise-db'
		},
		// Not keyed to any exercise: the two body figures behind the muscle map
		// (§4.6). attribution.json is this project's licence register, and MIT
		// requires the copyright notice to travel with the work — the About page
		// reads this file.
		{
			id: MUSCLE_FIGURE_ATTRIBUTION,
			source: 'body-highlighter',
			license: 'MIT',
			author: 'ELABBASSI Hicham and Stefan Poindl',
			sourceUrl: `https://www.npmjs.com/package/${MODEL_PACKAGE}`,
			covers: 'The front and back body figures on the exercise and muscle screens'
		},
		// The SIL Open Font License requires its notice to travel with the font,
		// which the printable sheet embeds a subset of (§16).
		{
			id: SHEET_FONT_ATTRIBUTION,
			source: 'noto-fonts',
			license: 'OFL-1.1',
			author: 'The Noto Project Authors',
			sourceUrl: 'https://github.com/notofonts/latin-greek-cyrillic',
			covers: 'The typeface embedded in the printable routine sheet'
		}
	];

	const outDir = join(ROOT, 'src/lib/catalog');
	await mkdir(outDir, { recursive: true });
	await writeFile(join(outDir, 'catalog.json'), JSON.stringify(catalog, null, '\t') + '\n');
	await writeFile(join(outDir, 'attribution.json'), JSON.stringify(attribution, null, '\t') + '\n');

	// No catalog-for-llm.json here any more (§14, amended 2026-07-30): it is
	// generated in the browser from catalog.json so it can be filtered to what the
	// user owns, which a build-time artefact cannot possibly know.

	const perCategory: Record<string, number> = {};
	for (const e of catalog) perCategory[e.category] = (perCategory[e.category] ?? 0) + 1;
	const perEquipment: Record<string, string> = {};
	for (const id of ALL_EQUIPMENT) {
		const n = catalog.filter((e) => e.equipment.includes(id)).length;
		perEquipment[id] = `${n}/${curation.budgets[id] ?? '-'}`;
	}
	const reachable = catalog.filter((e) => !e.equipment.some((t) => GATED.includes(t))).length;
	console.log('\n=== Summary ===');
	console.log(`Total exercises: ${catalog.length}`);
	console.log(`Reachable with nothing owned: ${reachable}/${curation.budgets.ungated}`);
	console.log(`Per equipment (kept/budget): ${JSON.stringify(perEquipment)}`);
	console.log(`Per category: ${JSON.stringify(perCategory)}`);
	console.log(`Per source: free-exercise-db=${catalog.length}`);
	console.log(`Dropped (zero media): ${dropped.length}${dropped.length ? ' -> ' + dropped.join(', ') : ''}`);
	console.log(
		`Duplicate frames skipped: ${duplicateFrames.length}${
			duplicateFrames.length ? ' -> ' + duplicateFrames.sort().join(', ') : ''
		}`
	);
	const single = catalog.filter((e) => e.media.length === 1).length;
	console.log(`Exercises with a single frame: ${single}, with two: ${catalog.length - single}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
