import type { Locale } from '../i18n/index.js';
import type { Exercise, ExerciseId } from '../types.js';

/**
 * Exercise names per language — the seam, deliberately empty (docs/SPEC.md §16).
 *
 * **The catalog's text stays English, and this is where that decision is kept
 * honest.** `catalog.json` is generated by `scripts/build-catalog.ts` from
 * free-exercise-db: 166 names, 577 instruction steps and 216 aliases of English
 * data, not copy anybody here wrote. Translating it is a different project from
 * translating the interface, and three things make it one to take on
 * deliberately rather than by accident:
 *
 * - **The build script would overwrite it.** §5 requires the same inputs to
 *   produce byte-identical output, so a translation living inside `catalog.json`
 *   is destroyed by the next `npm run build:catalog`. It has to live in a
 *   hand-authored file next to it — which is what this is, and the same
 *   arrangement `ladders.ts` and the muscle glossary already use.
 * - **The resolver must not follow it.** §6.3 matches imported names against the
 *   English `name` and `aliases`, and the LLM prompt (§14) quotes English ids.
 *   Those stay English whatever this file says, so a translated name changes
 *   what is *shown* and never what is *matched*.
 * - **Speech would have to follow it.** §7 fixes the spoken language to English
 *   because the names being read out are English. A half-translated catalog
 *   would make that sentence half-true, which is worse than either end of it.
 *
 * So: adding Danish names is dropping a `da` entry into `NAMES` below. Nothing
 * else in the app has to change, and `exerciseName()` already resolves through
 * it everywhere a name is shown.
 */
type NameOverrides = Partial<Record<Locale, Partial<Record<ExerciseId, string>>>>;

const NAMES: NameOverrides = {
	// No locale translates the catalog today. See the note above before adding
	// one: it is a decision about speech and about the importer, not only about
	// words on a screen.
};

/**
 * What to call an exercise in this language — its English catalog name unless a
 * locale has been given something better.
 */
export function exerciseName(exercise: Exercise, locale: Locale): string {
	return NAMES[locale]?.[exercise.id] ?? exercise.name;
}

/** The same, by id, for the places that have one and not the whole exercise. */
export function exerciseNameById(
	id: ExerciseId,
	locale: Locale,
	lookup: (id: ExerciseId) => Exercise | undefined
): string {
	return NAMES[locale]?.[id] ?? lookup(id)?.name ?? id;
}

/** Whether this locale has any catalog names of its own at all. */
export function hasTranslatedNames(locale: Locale): boolean {
	return Object.keys(NAMES[locale] ?? {}).length > 0;
}
